package org.apache.cordova.twiliovideo;

public enum CallEvent {
    OPENED,
    CONNECTED,
    CONNECT_FAILURE,
    DISCONNECTED,
    DISCONNECTED_WITH_ERROR,
    RECONNECTING,
    RECONNECTED,
    PARTICIPANT_CONNECTED,
    PARTICIPANT_DISCONNECTED,
    REMOTE_VIDEO_TRACK_ADDED,
    REMOTE_VIDEO_TRACK_REMOVED,
    HANG_UP,
    CLOSED,
    PERMISSIONS_REQUIRED
}
