package org.apache.cordova.twiliovideo;

/**
 * Created by rpanadero on 13/9/18.
 */

public enum CallEvent { OPENED, CONNECTED, CONNECT_FAILURE, DISCONNECTED, PARTICIPANT_CONNECTED
    , PARTICIPANT_DISCONNECTED, AUDIO_TRACK_ADDED, AUDIO_TRACK_REMOVED, VIDEO_TRACK_ADDED
    , VIDEO_TRACK_REMOVED, CLOSED }
